

#define DEBUG
#define INFO
#define BAUDS_RATE 115200

#define NBREMANANCE	4

#define PIN_HOUR 4
#define PIN_MINUTE 5
#define PIN_SECONDE 5
#define PIN_DIXSECONDE 5

#define NBPIXELS_HOUR 12
#define NBPIXELS_MINUTE 24	
#define NBPIXELS_SECONDE 24	
#define NBPIXELS_DIXSECONDE 24	

#define BRIGHTNESS_HOUR 50
#define BRIGHTNESS_MINUTE 50
#define BRIGHTNESS_SECONDE 50
#define BRIGHTNESS_DIXSECONDE 50

#define GAMMA 0

// PIN
#define PIN_MODE 2
#define PIN_COLOR 3